//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNP_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Proposal
    {
        public int ID { get; set; }
        public string CRM_QUOTE_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<double> ValueTotal { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ClientAccountNumber { get; set; }
        public string AccountManager { get; set; }
        public Nullable<bool> ToDelete { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string StatusCRM1 { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> StatusCRM { get; set; }
        public Nullable<double> TaxaCopiaTotal { get; set; }
        public Nullable<double> SobreValorizacao { get; set; }
        public Nullable<double> ValueComission { get; set; }
    }
}
