//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotineClientEmailReceive
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD_Contrato
    {
        public int ID { get; set; }
        public Nullable<int> ProposalID { get; set; }
        public string QuoteNumber { get; set; }
        public string PathContracto { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> ContratoValidado { get; set; }
        public Nullable<bool> ContratoGerado { get; set; }
        public Nullable<System.DateTime> Assinatura { get; set; }
        public Nullable<int> SystemAssinaturaID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string FilenameContracto { get; set; }
        public Nullable<int> TipoContratoID { get; set; }
        public string ComentariosGC { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> Retorno { get; set; }
        public string ComentariosDevolucao { get; set; }
        public Nullable<int> MotivoID { get; set; }
        public Nullable<int> DevolucaoMotivoID { get; set; }
        public string Pasta { get; set; }
        public Nullable<bool> IsFacturacao { get; set; }
        public string DocusignEnvelopeID { get; set; }
        public Nullable<int> SapVersion { get; set; }
    }
}
