//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotineClientEmailReceive
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD_Email_Log
    {
        public int ID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string QuoteNumber { get; set; }
        public string NrClient { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> NrAttachedFiles { get; set; }
        public string EmailReceived { get; set; }
        public string EmailSent { get; set; }
        public string Subject { get; set; }
        public string body { get; set; }
    }
}
