//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotineClientEmailSent
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Clientes
    {
        public int ID { get; set; }
        public string accountnumber { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string PostalCode { get; set; }
        public string address1_line1 { get; set; }
        public string emailaddress1 { get; set; }
        public string NIF { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public string Holding { get; set; }
        public string GMA { get; set; }
        public string GMA_Identifier { get; set; }
        public string Industry { get; set; }
        public string Segment { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string City { get; set; }
        public Nullable<bool> IsClienteBB { get; set; }
        public string telephone1 { get; set; }
        public string NUS_ACCOUNT { get; set; }
    }
}
