//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotineClientEmailSent
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD_PA5_DocumentProposal
    {
        public int ID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> PA5DocumentID { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> IsToSend { get; set; }
    }
}
