//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotineClientEmailSent
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD_PA5_DocumentType
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> IsSolicted { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
